# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-05 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBBS', '0002_auto_20160905_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbup',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
