# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-07 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBBS', '0003_thumbup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(default='test summary', max_length=255),
            preserve_default=False,
        ),
    ]
