# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-11 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBBS', '0004_article_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='data',
            new_name='date',
        ),
    ]
